# Generated by Django 5.1.4 on 2025-01-02 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_remove_healthcaresuggestion_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('start_month', models.IntegerField()),
                ('end_month', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('primary_advice', models.TextField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='healthcare.season')),
            ],
        ),
    ]
