# Generated by Django 5.1.4 on 2025-01-04 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0004_season_seasonaldisease'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailed_preventive_measures', models.TextField(help_text='Detailed suggestions for preventing seasonal diseases.')),
                ('general_season_tips', models.CharField(help_text='Short tips for general health during the season.', max_length=255)),
                ('additional_seasonal_advice', models.TextField(help_text='Additional health advice for this season.')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_suggestions', to='healthcare.season')),
            ],
        ),
    ]
